# Generated by Django 3.2.9 on 2021-11-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='research',
            field=models.ManyToManyField(related_name='researchoutput', to='dirsysapp.ResearchOutput'),
        ),
    ]
