# Generated by Django 3.2.9 on 2021-11-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0003_remove_enduser_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
