# Generated by Django 3.2.9 on 2021-11-13 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0004_enduser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_output', to='dirsysapp.researchoutput'),
        ),
    ]
