# Generated by Django 3.2.9 on 2021-11-13 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dirsysapp', '0006_remove_enduser_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchoutput',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
