# Generated by Django 3.2.9 on 2021-11-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0007_alter_researchoutput_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='research_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dirsysapp.researchoutput'),
        ),
    ]
