# Generated by Django 3.2.9 on 2021-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0008_enduser_research_output'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchoutput',
            options={},
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='research_output',
        ),
        migrations.AlterField(
            model_name='researchoutput',
            name='author',
            field=models.ManyToManyField(to='dirsysapp.EndUser'),
        ),
    ]
