# Generated by Django 3.2.9 on 2021-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0015_alter_program_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Nursing Program', 'Nursing Program'), ('Hospitality Management Program', 'Hospitality Management Program'), ('Tourism Management Program', 'Tourism Management Program'), ('Accountancy Program', 'Accountancy Program'), ('Liberal Arts Program', 'Liberal Arts Program'), ('Criminology Program', 'Criminology Program'), ('Business Administration Program', 'Business Administration Program'), ('Civil Engineering Program', 'Civil Engineering Program'), ('Elementary Education Program', 'Elementary Education Program'), ('Secondary Education Program', 'Secondary Education Program'), ('Computer Science Program', 'Computer Science Program'), ('Faculty Program', 'Faculty Program'), ('Research Office Program', 'Research Office Program')], max_length=31),
        ),
    ]
